name: njord-publisher-sonatype-nx3

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus-repository
    ports:
      - "8081:8081"
    volumes:
      - ./data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=
          -Xms512m
          -Xmx1024m
          -XX:MaxDirectMemorySize=512m
          -Djava.util.prefs.userRoot=/nexus-data/javaprefs
          -Dnexus.security.randompassword=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  nexus-data:
    driver: local
