name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@release-37
    with:
      jdk-matrix: '[ "11", "17", "21", "24" ]'
      maven-matrix: '[ "3.9.9" ]' # IT does the mvn matrix
      maven-test: './mvnw clean verify -e -B -V -P run-its -f it'

